In [1]:
from google.colab import files

uploaded = files.upload()

Saving Bookings-100000-Rows.xlsx to Bookings-100000-Rows.xlsx

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("Bookings-100000-Rows.xlsx")

print("Shape:", df.shape)
df.head()

Shape: (103024, 20)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(2), object(13)
memory usage: 15.7+ MB

In [22]:
df.tail()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [23]:
df.isnull().sum().sort_values(ascending=False)

Incomplete_Rides_Reason       99098
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
V_TAT                         39057
Customer_Rating               39057
Payment_Method                39057
Incomplete_Rides              39057
C_TAT                         39057
Driver_Ratings                39057
Booking_ID                        0
Time                              0
Date                              0
Booking_Status                    0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
Customer_ID                       0
Booking_Value                     0
Ride_Distance                     0
Vehicle Images                    0
dtype: int64

In [24]:
df.describe(include='all')

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
count,103024,103024,103024,103024,103024,103024,103024,103024,63967.000000,63967.000000,10499,18434,63967,3926,103024.000000,63967,103024.000000,63967.000000,63967.000000,103024
unique,NaN,1440,103024,4,94544,7,50,50,NaN,NaN,5,4,2,3,NaN,4,NaN,NaN,NaN,7
top,NaN,00:53:00,CNR3204013257,Success,CID954071,Prime Sedan,Banashankari,Peenya,NaN,NaN,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,NaN,Cash,NaN,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
freq,NaN,101,1,63967,5,14877,2201,2159,NaN,NaN,3175,6542,60041,1601,NaN,35022,NaN,NaN,NaN,14877
mean,2024-07-16 11:31:38.879678720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170.876952,84.873372,NaN,NaN,NaN,NaN,548.751883,NaN,14.189927,3.997457,3.998313,NaN
min,2024-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,25.000000,NaN,NaN,NaN,NaN,100.000000,NaN,0.000000,3.000000,3.000000,NaN
25%,2024-07-08 18:41:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,55.000000,NaN,NaN,NaN,NaN,242.000000,NaN,0.000000,3.500000,3.500000,NaN
50%,2024-07-16 11:23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.000000,85.000000,NaN,NaN,NaN,NaN,386.000000,NaN,8.000000,4.000000,4.000000,NaN
75%,2024-07-24 05:18:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.000000,115.000000,NaN,NaN,NaN,NaN,621.000000,NaN,26.000000,4.500000,4.500000,NaN
max,2024-07-31 23:58:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.000000,145.000000,NaN,NaN,NaN,NaN,2999.000000,NaN,49.000000,5.000000,5.000000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.803640,36.005100,NaN,NaN,NaN,NaN,536.541221,NaN,15.776270,0.576834,0.578957,NaN

In [25]:
print(df.shape)
print(df.columns.tolist())

(103024, 20)
['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT', 'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver', 'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value', 'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating', 'Vehicle Images']

In [26]:

nulls = df.isnull().sum()
nulls = nulls[nulls > 0]
print(nulls.sort_values(ascending=False))

Incomplete_Rides_Reason       99098
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
V_TAT                         39057
C_TAT                         39057
Incomplete_Rides              39057
Payment_Method                39057
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [27]:
print(df['Time'].head(20))
print(df['Time'].dtype)

0     14:00:00
1     22:20:00
2     19:59:00
3     03:15:00
4     09:02:00
5     04:42:00
6     09:51:00
7     11:12:00
8     19:19:00
9     01:31:00
10    23:33:00
11    04:03:00
12    13:18:00
13    18:55:00
14    09:54:00
15    10:25:00
16    23:50:00
17    23:42:00
18    11:11:00
19    14:44:00
Name: Time, dtype: object
object

In [28]:
df['Booking_Status'].value_counts(dropna=False)

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

In [29]:
df['Incomplete_Rides_Reason'] = (
    df['Incomplete_Rides_Reason']
    .fillna('Ride Completed')
)

In [30]:
df['Canceled_Rides_by_Customer'] = (
    df['Canceled_Rides_by_Customer']
    .fillna('Not Cancelled')
)

In [31]:
df['Canceled_Rides_by_Driver'] = (
    df['Canceled_Rides_by_Driver']
    .fillna('Not Cancelled')
)

In [32]:
df['Incomplete_Rides'] = (
    df['Incomplete_Rides']
    .fillna('No')
)

In [34]:
df['Driver_Ratings'] = (
    df['Driver_Ratings']
    .fillna(0)
)

df['Customer_Rating'] = (
    df['Customer_Rating']
    .fillna(0)
)

In [35]:
df['Payment_Method'] = (
    df['Payment_Method']
    .fillna('Not Applicable')
)

In [36]:
print(df['V_TAT'].dtype)
print(df['C_TAT'].dtype)

float64
float64

In [37]:
df['V_TAT'] = df['V_TAT'].fillna(0)
df['C_TAT'] = df['C_TAT'].fillna(0)

In [38]:
df.isnull().sum().sort_values(ascending=False)

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
Vehicle Images                0
dtype: int64

In [39]:
df.drop(
    columns=['Vehicle Images'],
    inplace=True
)

In [40]:
df['Date'] = pd.to_datetime(df['Date'])

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.month_name()
df['Weekday'] = df['Date'].dt.day_name()

df['Hour'] = pd.to_datetime(
    df['Time'].astype(str),
    format='%H:%M:%S'
).dt.hour

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  object
 11  Canceled_Rides_by_Driver    103024 non-null  object
 12  Incomplete_Rides            103024 non-null  object
 13  Incomplete_Rides_Reason     103024 non-null  object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              103024 non-null  float64
 18  Customer_Rating             103024 non-null  float64
 19  Year                        103024 non-null  int32
 20  Month                       103024 non-null  int32
 21  Month_Name                  103024 non-null  object
 22  Weekday                     103024 non-null  object
 23  Hour                        103024 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(3), int64(2), object(14)
memory usage: 17.7+ MB

In [42]:
df['Booking_Status'].value_counts()

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

In [44]:
# Revenue per KM
df['Revenue_per_KM'] = (
    df['Booking_Value'] /
    df['Ride_Distance']
)

# Peak Hours
df['Peak_Hour'] = np.where(
    ((df['Hour'] >= 7) & (df['Hour'] <= 10)) |
    ((df['Hour'] >= 17) & (df['Hour'] <= 21)),
    'Peak',
    'Non-Peak'
)

# Weekend Flag
df['Is_Weekend'] = np.where(
    df['Weekday'].isin(['Saturday','Sunday']),
    'Weekend',
    'Weekday'
)

# Rating Bucket
df['Driver_Rating_Group'] = pd.cut(
    df['Driver_Ratings'],
    bins=[-1,2,3,4,5],
    labels=['Poor','Average','Good','Excellent']
)

**EDA** **PERFORM**

In [45]:
total_revenue = df['Booking_Value'].sum()
print(f"Revenue = ₹{total_revenue:,.0f}")

Revenue = ₹56,534,614

In [46]:
success_rate = (
    (df['Booking_Status']=='Success')
    .mean()*100
)

print(success_rate)

62.089416058394164

In [47]:
cancel_rate = (
    df['Booking_Status']
    .str.contains('Canceled')
    .mean()*100
)

print(cancel_rate)

28.0837474763162

In [50]:
vehicle_revenue = (
    df.groupby('Vehicle_Type')
      ['Booking_Value']
      .sum()
      .sort_values(ascending=False)
)

vehicle_revenue

Vehicle_Type
Prime Sedan    8298612
eBike          8181523
Auto           8092210
Prime Plus     8050889
Mini           7990996
Bike           7987054
Prime SUV      7933330
Name: Booking_Value, dtype: int64

In [51]:
df['Vehicle_Type'].value_counts()

Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64

In [52]:
hourly = (
    df.groupby('Hour')
      .size()
      .sort_values(ascending=False)
)

hourly.head(10)

Hour
12    4408
15    4376
8     4374
17    4353
9     4347
21    4343
10    4334
1     4329
0     4318
2     4305
dtype: int64

In [54]:
hour_revenue = (
    df.groupby('Hour')
      ['Booking_Value']
      .sum()
)

In [55]:
df['Pickup_Location'].value_counts().head(10)

Pickup_Location
Banashankari        2201
Yeshwanthpur        2139
RT Nagar            2135
Indiranagar         2133
Sahakar Nagar       2126
Basavanagudi        2120
Ramamurthy Nagar    2116
Vijayanagar         2113
Tumkur Road         2105
Cox Town            2100
Name: count, dtype: int64

In [56]:
df['Drop_Location'].value_counts().head(10)

Drop_Location
Peenya           2159
Mysore Road      2148
MG Road          2128
Hennur           2120
HSR Layout       2117
Sarjapur Road    2108
Koramangala      2105
Marathahalli     2104
Vijayanagar      2103
Hebbal           2097
Name: count, dtype: int64

In [57]:
payment = (
    df.groupby('Payment_Method')
      .agg({
          'Booking_Value':'sum',
          'Booking_ID':'count'
      })
)
payment

                Booking_Value  Booking_ID
Payment_Method
Cash                 19260316       35022
Credit Card           1312793        2435
Debit Card             338922         629
Not Applicable       21454147       39057
UPI                  14168436       25881

**BUSINESS INSIGHTS**

In [58]:
cancel_vehicle = pd.crosstab(
    df['Vehicle_Type'],
    df['Booking_Status']
)

cancel_vehicle

Booking_Status,Canceled by Customer,Canceled by Driver,Driver Not Found,Success
Vehicle_Type,,,,
Auto,1503,2675,1410,9167
Bike,1537,2559,1432,9134
Mini,1505,2584,1427,9036
Prime Plus,1474,2683,1475,9075
Prime SUV,1498,2648,1513,8996
Prime Sedan,1470,2591,1437,9379
eBike,1512,2694,1430,9180

In [59]:
df.groupby('Vehicle_Type')[
    'Driver_Ratings'
].mean().sort_values(ascending=False)

Vehicle_Type
Prime Sedan    2.515870
Auto           2.487570
eBike          2.482580
Bike           2.482322
Mini           2.479316
Prime Plus     2.466846
Prime SUV      2.458956
Name: Driver_Ratings, dtype: float64

In [60]:
df.groupby('Weekday')[
    'Booking_Value'
].sum().sort_values(ascending=False)

Weekday
Tuesday      9311131
Monday       9273756
Wednesday    9040761
Thursday     7354322
Saturday     7301461
Friday       7201319
Sunday       7051864
Name: Booking_Value, dtype: int64

In [61]:
df.to_csv(
    "uber_cleaned.csv",
    index=False
)

In [63]:
kpi_summary = pd.DataFrame({
    'Metric': [
        'Total Revenue',
        'Highest Revenue Vehicle',
        'Most Used Payment Method',
        'Peak Booking Hour'
    ],
    'Value': [
        total_revenue,
        'Prime Sedan',
        'Cash',
        '12:00'
    ]
})

kpi_summary

                     Metric        Value
0             Total Revenue     56534614
1   Highest Revenue Vehicle  Prime Sedan
2  Most Used Payment Method         Cash
3         Peak Booking Hour        12:00

In [64]:
df.to_csv("uber_analytics_final.csv", index=False)

In [65]:
from google.colab import files
files.download("uber_analytics_final.csv")